//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademico.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleto
    {
        public int IdBoleto { get; set; }
        public int IdMatricula { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime DataVencimento { get; set; }
        public string Status { get; set; }
    
        public virtual Matricula Matricula { get; set; }
    }
}
