//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaAcademico.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.Matricula = new HashSet<Matricula>();
        }
    
        public int IdCurso { get; set; }
        public string Nome { get; set; }
        public int DuracaoSemestres { get; set; }
    
        public virtual ICollection<Matricula> Matricula { get; set; }
    }
}
